spring:
  application:
    name: fxMarketDataConnector

server:
  port: 4080

kafka:
  bootstrap-servers: localhost:9092
  topic: fx_rates

vendor:
  market:
    data:
      stub:
        url: "http://localhost:3080"
