spring:
  application:
    name: fxMarketDataConnector

server:
  port: 8080

kafka:
  bootstrap-servers: PLAINTEXT://kafka:9092
  topic: fx_rates_kafka

vendor:
  market:
    data:
      stub:
        url: "http://fx-market-data-stub-svc:3080"
