spring:
  application:
    name: fxMarketDataConnector

server:
  port: 4080

kafka:
  bootstrap-servers: PLAINTEXT://broker:29092
  topic: fx_rates_kafka

vendor:
  market:
    data:
      stub:
        url: http://fx-market-stub:3080
