spring:
  application:
    name: fxMarketDataConnector

server:
  port: 4080

kafka:
  bootstrap-servers: PLAINTEXT://broker:29092

vendor:
  market:
    data:
      stub:
        url: http://market-data-stub:3080
