spring:
  application:
    name: fxMarketCamelDataConnector

server:
  port: 4080

kafka:
  bootstrap-servers: localhost:9092

vendor:
  market:
    data:
      stub:
        url: "http://localhost:3080"
