spring:
  application:
    name: fxMarketCamelDataConnector

kafka:
  bootstrap-servers: PLAINTEXT://kafka:9092

vendor:
  market:
    data:
      stub:
        url: "http://fx-market-data-stub-svc:3080"
