##### APPLICATIONS

apps:
  ###################################
  ##### FX MARKET CONNECTOR APP #####
  ###################################
  fxmarketconnector:
    name: fx-market-connector
    image:
      repository: localhost:5001/fx-market-services/fx-market-connector
#      tag: 0.0.0

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv:
      - name: SERVER_PORT
        value: "8080"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "PLAINTEXT://kafka:9092"
      - name: VENDOR_MARKET_DATA_STUB_URL
        value: "http://fx-market-data-stub-svc:3080"
      - name: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka.fxmarket.svc.cluster.local:9092
      - name: KAFKA_LISTENERS
        value: PLAINTEXT://0.0.0.0:9092


    resources:
      limits:
        cpu: 1
        memory: 3072Mi
      requests:
        cpu: 500m
        memory: 3072Mi

    volumes: []
      # - name: server-certs
      #   secretName: api-fxmarketconnector
      #   mountPath: /opt/certs/fxmarketconnector
      #   optional: true
      # - name: mtls-certs2
      #   secretName: mtls-certs2
      #   mountPath: /opt/certs/mtls2
    #   optional: true

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    initContainers: {}
    imagePullSecrets: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}


  ###################################
  ##### FX MARKET PROCESSOR APP #####
  ###################################
  fxmarketprocessor:
    name: fx-market-processor
    image:
      repository: localhost:5001/fx-market-services/fx-market-processor
#      tag: 0.0.0

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv:
      - name: SERVER_PORT
        value: "8080"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "PLAINTEXT://kafka:9092"

    resources:
      limits:
        cpu: 1
        memory: 3072Mi
      requests:
        cpu: 500m
        memory: 3072Mi

    volumes: []
      # - name: server-certs
      #   secretName: api-fxmarketconnector
      #   mountPath: /opt/certs/fxmarketconnector
      #   optional: true
      # - name: mtls-certs2
      #   secretName: mtls-certs2
    #   mountPath: /opt/certs/mtls2
    #   optional: true

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    initContainers: {}
    imagePullSecrets: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  ###################################
  ##### FLINK ORCHESTRATOR APP ######
  ###################################
  flinkorchestrator:
    name: flink-orchestrator
    image:
      repository: localhost:5001/fx-market-services/flink-orchestrator
    #      tag: 0.0.0

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 8080

    extraEnv:
      - name: SERVER_PORT
        value: "8080"
      - name: FLINK_URL
        value: "http://fx-flink-jobmanager:8081"

    resources:
      limits:
        cpu: 1
        memory: 3584Mi
      requests:
        cpu: 500m
        memory: 3584Mi

    volumes: []
      # - name: server-certs
      #   secretName: api-fxmarketconnector
      #   mountPath: /opt/certs/fxmarketconnector
      #   optional: true
    # - name: mtls-certs2
    #   secretName: mtls-certs2
    #   mountPath: /opt/certs/mtls2
    #   optional: true

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    initContainers: {}
    imagePullSecrets: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

