##### APPLICATIONS

apps:
###################################
####### FX MARKET DATA STUB #######
###################################
  fxmarketdatastub:
    name: fx-market-data-stub
    image:
      repository: localhost:5001/fx-market-externals/market-data-stub
#      tag: 0.0.0

    podAnnotations: {}

    service:
      type: ClusterIP
      port: 3080

    extraEnv: []

    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi

    volumes: []

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 80

    initContainers: {}
    imagePullSecrets: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}