// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxMarketMessage.proto

package com.fx.market.flink.processor.model;

public final class FxMarketMessage {
  private FxMarketMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_market_kafka_message_FxRateEventProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fx_market_kafka_message_FxRateProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fx_market_kafka_message_FxRateProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025fxMarketMessage.proto\022\033com.fx.market.k" +
      "afka.message\"^\n\020FxRateEventProto\022\021\n\ttime" +
      "stamp\030\001 \001(\t\0227\n\005rates\030\002 \003(\0132(.com.fx.mark" +
      "et.kafka.message.FxRateProto\"b\n\013FxRatePr" +
      "oto\022\014\n\004pair\030\001 \001(\t\022\024\n\014baseCurrency\030\002 \001(\t\022" +
      "\025\n\rquoteCurrency\030\003 \001(\t\022\013\n\003ask\030\004 \001(\t\022\013\n\003b" +
      "id\030\005 \001(\tB \n\034 com.fx.market.kafka.message" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fx_market_kafka_message_FxRateEventProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor,
        new String[] { "Timestamp", "Rates", });
    internal_static_com_fx_market_kafka_message_FxRateProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fx_market_kafka_message_FxRateProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fx_market_kafka_message_FxRateProto_descriptor,
        new String[] { "Pair", "BaseCurrency", "QuoteCurrency", "Ask", "Bid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
