// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxMarketMessage.proto

package com.fx.market.flink.processor.model;

/**
 * Protobuf type {@code com.fx.market.kafka.message.FxRateEventProto}
 */
public  final class FxRateEventProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fx.market.kafka.message.FxRateEventProto)
    FxRateEventProtoOrBuilder {
  // Use FxRateEventProto.newBuilder() to construct.
  private FxRateEventProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FxRateEventProto() {
    timestamp_ = "";
    rates_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FxRateEventProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            timestamp_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              rates_ = new java.util.ArrayList<FxRateProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            rates_.add(
                input.readMessage( FxRateProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        rates_ = java.util.Collections.unmodifiableList(rates_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateEventProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
             FxRateEventProto.class,  FxRateEventProto.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private volatile Object timestamp_;
  /**
   * <code>optional string timestamp = 1;</code>
   */
  public String getTimestamp() {
    Object ref = timestamp_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>optional string timestamp = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    Object ref = timestamp_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATES_FIELD_NUMBER = 2;
  private java.util.List<FxRateProto> rates_;
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  public java.util.List<FxRateProto> getRatesList() {
    return rates_;
  }
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  public java.util.List<? extends FxRateProtoOrBuilder>
      getRatesOrBuilderList() {
    return rates_;
  }
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  public int getRatesCount() {
    return rates_.size();
  }
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  public FxRateProto getRates(int index) {
    return rates_.get(index);
  }
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  public FxRateProtoOrBuilder getRatesOrBuilder(
      int index) {
    return rates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
    }
    for (int i = 0; i < rates_.size(); i++) {
      output.writeMessage(2, rates_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
    }
    for (int i = 0; i < rates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rates_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FxRateEventProto)) {
      return super.equals(obj);
    }
     FxRateEventProto other = (FxRateEventProto) obj;

    boolean result = true;
    result = result && getTimestamp()
        .equals(other.getTimestamp());
    result = result && getRatesList()
        .equals(other.getRatesList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    if (getRatesCount() > 0) {
      hash = (37 * hash) + RATES_FIELD_NUMBER;
      hash = (53 * hash) + getRatesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FxRateEventProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FxRateEventProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FxRateEventProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FxRateEventProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FxRateEventProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FxRateEventProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FxRateEventProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FxRateEventProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FxRateEventProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FxRateEventProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder( FxRateEventProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fx.market.kafka.message.FxRateEventProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fx.market.kafka.message.FxRateEventProto)
          FxRateEventProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateEventProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
               FxRateEventProto.class,  FxRateEventProto.Builder.class);
    }

    // Construct using  com.fx.market.kafka.message.FxRateEventProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRatesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      timestamp_ = "";

      if (ratesBuilder_ == null) {
        rates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        ratesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateEventProto_descriptor;
    }

    public FxRateEventProto getDefaultInstanceForType() {
      return  FxRateEventProto.getDefaultInstance();
    }

    public FxRateEventProto build() {
       FxRateEventProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public FxRateEventProto buildPartial() {
       FxRateEventProto result = new FxRateEventProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.timestamp_ = timestamp_;
      if (ratesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          rates_ = java.util.Collections.unmodifiableList(rates_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rates_ = rates_;
      } else {
        result.rates_ = ratesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FxRateEventProto) {
        return mergeFrom((FxRateEventProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom( FxRateEventProto other) {
      if (other ==  FxRateEventProto.getDefaultInstance()) return this;
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (ratesBuilder_ == null) {
        if (!other.rates_.isEmpty()) {
          if (rates_.isEmpty()) {
            rates_ = other.rates_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRatesIsMutable();
            rates_.addAll(other.rates_);
          }
          onChanged();
        }
      } else {
        if (!other.rates_.isEmpty()) {
          if (ratesBuilder_.isEmpty()) {
            ratesBuilder_.dispose();
            ratesBuilder_ = null;
            rates_ = other.rates_;
            bitField0_ = (bitField0_ & ~0x00000002);
            ratesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRatesFieldBuilder() : null;
          } else {
            ratesBuilder_.addAllMessages(other.rates_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
       FxRateEventProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FxRateEventProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object timestamp_ = "";
    /**
     * <code>optional string timestamp = 1;</code>
     */
    public String getTimestamp() {
      Object ref = timestamp_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string timestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string timestamp = 1;</code>
     */
    public Builder setTimestamp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string timestamp = 1;</code>
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }

    private java.util.List<FxRateProto> rates_ =
      java.util.Collections.emptyList();
    private void ensureRatesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        rates_ = new java.util.ArrayList<FxRateProto>(rates_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            FxRateProto,  FxRateProto.Builder, FxRateProtoOrBuilder> ratesBuilder_;

    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public java.util.List<FxRateProto> getRatesList() {
      if (ratesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rates_);
      } else {
        return ratesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public int getRatesCount() {
      if (ratesBuilder_ == null) {
        return rates_.size();
      } else {
        return ratesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public FxRateProto getRates(int index) {
      if (ratesBuilder_ == null) {
        return rates_.get(index);
      } else {
        return ratesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder setRates(
        int index,  FxRateProto value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.set(index, value);
        onChanged();
      } else {
        ratesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder setRates(
        int index,  FxRateProto.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.set(index, builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder addRates( FxRateProto value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.add(value);
        onChanged();
      } else {
        ratesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder addRates(
        int index,  FxRateProto value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.add(index, value);
        onChanged();
      } else {
        ratesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder addRates(
         FxRateProto.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.add(builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder addRates(
        int index,  FxRateProto.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.add(index, builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder addAllRates(
        Iterable<? extends FxRateProto> values) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rates_);
        onChanged();
      } else {
        ratesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder clearRates() {
      if (ratesBuilder_ == null) {
        rates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        ratesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public Builder removeRates(int index) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.remove(index);
        onChanged();
      } else {
        ratesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public  FxRateProto.Builder getRatesBuilder(
        int index) {
      return getRatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public FxRateProtoOrBuilder getRatesOrBuilder(
        int index) {
      if (ratesBuilder_ == null) {
        return rates_.get(index);  } else {
        return ratesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public java.util.List<? extends FxRateProtoOrBuilder>
         getRatesOrBuilderList() {
      if (ratesBuilder_ != null) {
        return ratesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rates_);
      }
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public  FxRateProto.Builder addRatesBuilder() {
      return getRatesFieldBuilder().addBuilder(
           FxRateProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public  FxRateProto.Builder addRatesBuilder(
        int index) {
      return getRatesFieldBuilder().addBuilder(
          index,  FxRateProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
     */
    public java.util.List< FxRateProto.Builder>
         getRatesBuilderList() {
      return getRatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            FxRateProto,  FxRateProto.Builder, FxRateProtoOrBuilder>
        getRatesFieldBuilder() {
      if (ratesBuilder_ == null) {
        ratesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                FxRateProto,  FxRateProto.Builder, FxRateProtoOrBuilder>(
                rates_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        rates_ = null;
      }
      return ratesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.fx.market.kafka.message.FxRateEventProto)
  }

  // @@protoc_insertion_point(class_scope:com.fx.market.kafka.message.FxRateEventProto)
  private static final FxRateEventProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FxRateEventProto();
  }

  public static FxRateEventProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FxRateEventProto>
      PARSER = new com.google.protobuf.AbstractParser<FxRateEventProto>() {
    public FxRateEventProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FxRateEventProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FxRateEventProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FxRateEventProto> getParserForType() {
    return PARSER;
  }

  public FxRateEventProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

