// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxMarketMessage.proto

package com.fx.market.flink.processor.model;

public interface FxRateEventProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fx.market.kafka.message.FxRateEventProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string timestamp = 1;</code>
   */
  String getTimestamp();
  /**
   * <code>optional string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  java.util.List<FxRateProto>
      getRatesList();
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
   FxRateProto getRates(int index);
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  int getRatesCount();
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
  java.util.List<? extends FxRateProtoOrBuilder>
      getRatesOrBuilderList();
  /**
   * <code>repeated .com.fx.market.kafka.message.FxRateProto rates = 2;</code>
   */
   FxRateProtoOrBuilder getRatesOrBuilder(
      int index);
}
