// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxMarketMessage.proto

package com.fx.market.flink.processor.model;

/**
 * Protobuf type {@code com.fx.market.kafka.message.FxRateProto}
 */
public  final class FxRateProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fx.market.kafka.message.FxRateProto)
    FxRateProtoOrBuilder {
  // Use FxRateProto.newBuilder() to construct.
  private FxRateProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FxRateProto() {
    pair_ = "";
    baseCurrency_ = "";
    quoteCurrency_ = "";
    ask_ = "";
    bid_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FxRateProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            pair_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            baseCurrency_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            quoteCurrency_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            ask_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            bid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateProto_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
             FxRateProto.class,  FxRateProto.Builder.class);
  }

  public static final int PAIR_FIELD_NUMBER = 1;
  private volatile Object pair_;
  /**
   * <code>optional string pair = 1;</code>
   */
  public String getPair() {
    Object ref = pair_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pair_ = s;
      return s;
    }
  }
  /**
   * <code>optional string pair = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPairBytes() {
    Object ref = pair_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pair_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASECURRENCY_FIELD_NUMBER = 2;
  private volatile Object baseCurrency_;
  /**
   * <code>optional string baseCurrency = 2;</code>
   */
  public String getBaseCurrency() {
    Object ref = baseCurrency_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      baseCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>optional string baseCurrency = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBaseCurrencyBytes() {
    Object ref = baseCurrency_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      baseCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTECURRENCY_FIELD_NUMBER = 3;
  private volatile Object quoteCurrency_;
  /**
   * <code>optional string quoteCurrency = 3;</code>
   */
  public String getQuoteCurrency() {
    Object ref = quoteCurrency_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      quoteCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>optional string quoteCurrency = 3;</code>
   */
  public com.google.protobuf.ByteString
      getQuoteCurrencyBytes() {
    Object ref = quoteCurrency_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      quoteCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASK_FIELD_NUMBER = 4;
  private volatile Object ask_;
  /**
   * <code>optional string ask = 4;</code>
   */
  public String getAsk() {
    Object ref = ask_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ask_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ask = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAskBytes() {
    Object ref = ask_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_FIELD_NUMBER = 5;
  private volatile Object bid_;
  /**
   * <code>optional string bid = 5;</code>
   */
  public String getBid() {
    Object ref = bid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBidBytes() {
    Object ref = bid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPairBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pair_);
    }
    if (!getBaseCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, baseCurrency_);
    }
    if (!getQuoteCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quoteCurrency_);
    }
    if (!getAskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ask_);
    }
    if (!getBidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, bid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPairBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pair_);
    }
    if (!getBaseCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, baseCurrency_);
    }
    if (!getQuoteCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quoteCurrency_);
    }
    if (!getAskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ask_);
    }
    if (!getBidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, bid_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FxRateProto)) {
      return super.equals(obj);
    }
     FxRateProto other = (FxRateProto) obj;

    boolean result = true;
    result = result && getPair()
        .equals(other.getPair());
    result = result && getBaseCurrency()
        .equals(other.getBaseCurrency());
    result = result && getQuoteCurrency()
        .equals(other.getQuoteCurrency());
    result = result && getAsk()
        .equals(other.getAsk());
    result = result && getBid()
        .equals(other.getBid());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PAIR_FIELD_NUMBER;
    hash = (53 * hash) + getPair().hashCode();
    hash = (37 * hash) + BASECURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getBaseCurrency().hashCode();
    hash = (37 * hash) + QUOTECURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getQuoteCurrency().hashCode();
    hash = (37 * hash) + ASK_FIELD_NUMBER;
    hash = (53 * hash) + getAsk().hashCode();
    hash = (37 * hash) + BID_FIELD_NUMBER;
    hash = (53 * hash) + getBid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FxRateProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FxRateProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FxRateProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FxRateProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FxRateProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FxRateProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FxRateProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FxRateProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FxRateProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FxRateProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder( FxRateProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fx.market.kafka.message.FxRateProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fx.market.kafka.message.FxRateProto)
          FxRateProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
               FxRateProto.class,  FxRateProto.Builder.class);
    }

    // Construct using  com.fx.market.kafka.message.FxRateProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pair_ = "";

      baseCurrency_ = "";

      quoteCurrency_ = "";

      ask_ = "";

      bid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return  FxMarketMessage.internal_static_com_fx_market_kafka_message_FxRateProto_descriptor;
    }

    public FxRateProto getDefaultInstanceForType() {
      return  FxRateProto.getDefaultInstance();
    }

    public FxRateProto build() {
       FxRateProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public FxRateProto buildPartial() {
       FxRateProto result = new FxRateProto(this);
      result.pair_ = pair_;
      result.baseCurrency_ = baseCurrency_;
      result.quoteCurrency_ = quoteCurrency_;
      result.ask_ = ask_;
      result.bid_ = bid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FxRateProto) {
        return mergeFrom((FxRateProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom( FxRateProto other) {
      if (other ==  FxRateProto.getDefaultInstance()) return this;
      if (!other.getPair().isEmpty()) {
        pair_ = other.pair_;
        onChanged();
      }
      if (!other.getBaseCurrency().isEmpty()) {
        baseCurrency_ = other.baseCurrency_;
        onChanged();
      }
      if (!other.getQuoteCurrency().isEmpty()) {
        quoteCurrency_ = other.quoteCurrency_;
        onChanged();
      }
      if (!other.getAsk().isEmpty()) {
        ask_ = other.ask_;
        onChanged();
      }
      if (!other.getBid().isEmpty()) {
        bid_ = other.bid_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
       FxRateProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FxRateProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object pair_ = "";
    /**
     * <code>optional string pair = 1;</code>
     */
    public String getPair() {
      Object ref = pair_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pair_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string pair = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPairBytes() {
      Object ref = pair_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pair_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string pair = 1;</code>
     */
    public Builder setPair(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pair_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string pair = 1;</code>
     */
    public Builder clearPair() {
      
      pair_ = getDefaultInstance().getPair();
      onChanged();
      return this;
    }
    /**
     * <code>optional string pair = 1;</code>
     */
    public Builder setPairBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pair_ = value;
      onChanged();
      return this;
    }

    private Object baseCurrency_ = "";
    /**
     * <code>optional string baseCurrency = 2;</code>
     */
    public String getBaseCurrency() {
      Object ref = baseCurrency_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        baseCurrency_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string baseCurrency = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBaseCurrencyBytes() {
      Object ref = baseCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        baseCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string baseCurrency = 2;</code>
     */
    public Builder setBaseCurrency(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      baseCurrency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string baseCurrency = 2;</code>
     */
    public Builder clearBaseCurrency() {
      
      baseCurrency_ = getDefaultInstance().getBaseCurrency();
      onChanged();
      return this;
    }
    /**
     * <code>optional string baseCurrency = 2;</code>
     */
    public Builder setBaseCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      baseCurrency_ = value;
      onChanged();
      return this;
    }

    private Object quoteCurrency_ = "";
    /**
     * <code>optional string quoteCurrency = 3;</code>
     */
    public String getQuoteCurrency() {
      Object ref = quoteCurrency_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quoteCurrency_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string quoteCurrency = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQuoteCurrencyBytes() {
      Object ref = quoteCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quoteCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string quoteCurrency = 3;</code>
     */
    public Builder setQuoteCurrency(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quoteCurrency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string quoteCurrency = 3;</code>
     */
    public Builder clearQuoteCurrency() {
      
      quoteCurrency_ = getDefaultInstance().getQuoteCurrency();
      onChanged();
      return this;
    }
    /**
     * <code>optional string quoteCurrency = 3;</code>
     */
    public Builder setQuoteCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quoteCurrency_ = value;
      onChanged();
      return this;
    }

    private Object ask_ = "";
    /**
     * <code>optional string ask = 4;</code>
     */
    public String getAsk() {
      Object ref = ask_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ask_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string ask = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAskBytes() {
      Object ref = ask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ask = 4;</code>
     */
    public Builder setAsk(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ask = 4;</code>
     */
    public Builder clearAsk() {
      
      ask_ = getDefaultInstance().getAsk();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ask = 4;</code>
     */
    public Builder setAskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ask_ = value;
      onChanged();
      return this;
    }

    private Object bid_ = "";
    /**
     * <code>optional string bid = 5;</code>
     */
    public String getBid() {
      Object ref = bid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string bid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBidBytes() {
      Object ref = bid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bid = 5;</code>
     */
    public Builder setBid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bid = 5;</code>
     */
    public Builder clearBid() {
      
      bid_ = getDefaultInstance().getBid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bid = 5;</code>
     */
    public Builder setBidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.fx.market.kafka.message.FxRateProto)
  }

  // @@protoc_insertion_point(class_scope:com.fx.market.kafka.message.FxRateProto)
  private static final FxRateProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FxRateProto();
  }

  public static FxRateProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FxRateProto>
      PARSER = new com.google.protobuf.AbstractParser<FxRateProto>() {
    public FxRateProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FxRateProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FxRateProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FxRateProto> getParserForType() {
    return PARSER;
  }

  public FxRateProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

