@startuml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v19.0/dist/AWSCommon.puml
!include <k8s/Common>
!include <k8s/Context>
!include <k8s/Simplified>
!include <k8s/OSS/all>
!include <kubernetes/k8s-sprites-unlabeled-25pct>

title FX Market Data Team - Detail Level Architecture Diagram
footer FX Market Data Team - Detail Level Architecture Diagram
left to right direction

package "Bloomberg" #DodgerBlue {
    component [B-PIPE] #SteelBlue
}

component "Visa AWS Direct Link" #DodgerBlue {
}

Bloomberg --|> "Visa AWS Direct Link"

node "Version 1" {
    package "Flink Cluster" as F_KC22 #LightGreen {
        package "Bloomberg FxMarketConnector in Flink - Flink task" as FS_FxMarketConnector2 #IndianRed {
              component "see B-PIPE SubscriptionExample.Java" as ex2 #grey
               component "Java 11" as FS_FxMarketConnectorTools2 #LightSteelBlue
        }
        "Visa AWS Direct Link" --|>FS_FxMarketConnector2 : Stream
        package "FlinkRedisSynk - Flink Task" as T2 #IndianRed {
               component "FlinkRedisSynk" as F_KS2 #grey
               component "Java 11" #LightSteelBlue
        }
    }
    FS_FxMarketConnector2 --> T2 : Stream
}

node "Version 2" {
    package "Bloomberg FxMarketConnector outside Flink"  #DodgerBlue {
           component "see B-PIPE SubscriptionExample.Java" as ex #grey
           component "Java 11" #LightSteelBlue
    }
    "Visa AWS Direct Link" --|> "Bloomberg FxMarketConnector outside Flink" : Stream
    package "Flink Cluster" #LightGreen {
        package "FxMarketConnector - Flink Task" as FS_FxMarketConnector #IndianRed {
               component "Java 11" as FS_FxMarketConnectorTools #LightSteelBlue
        }
        package "FlinkRedisSynk - Flink Task" #IndianRed {
               component "FlinkRedisSynk" as F_KS #grey
               component "Java 21" #LightSteelBlue
        }
    }
    "Bloomberg FxMarketConnector outside Flink" --|> FS_FxMarketConnector : Stream \n(websocket or SSE ?)
    FS_FxMarketConnector --> "F_KS" : Stream
}

@enduml