@startmindmap

skin rose

title 25/2/2025 Status for Ticket [29] Flink Custom Connector PoC

<style>

node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    LineColor blue
    LineThickness 3.0
}

rootNode {
    LineStyle 8.0;3.0
    LineColor blue
    BackgroundColor lightgreen
    LineThickness 3.0
    RoundCorner 0
    Shadowing 5
}

leafNode {
    LineStyle 1
    LineColor red
    LineThickness 1.0
    RoundCorner 20
    Padding 3
}

arrow {
    LineStyle 4
    LineThickness 1
    LineColor blue
}
</style>

* Flink\n1.20.1
** DONE\nupgrade to Flink 1.20.1\n on local and \non k8s\ninstallations
** sources
*** compile: ok with jdk 8,11,17,21
*** tests: ko with jdk 8,11,17,21
*** note: maven is th build tool used

left side

** documenting
*** WIP only from the site and from the source code
*** Abbandoned books not found
*** flink source code and examples
**** WIP file source unbounded
**** websocket unbounded - deprecated sources
** WIP write the code for the source
*** DONE SseSourceSplit
*** AbstractSseSource, SseSource
*** SseSourceBuilder
*** SseSourceSplitSerializer
*** use SourceReaderBase SplitReader SplitChange RecordsWithSplitIds RecordEmitter ? \nsee https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface#FLIP27:RefactorSourceInterface-SourceSplit
** WIP testing locally
** WIP testing perf locally
** others

@endwbs