spring:
  application:
    name: fxMarketDataConnector
  kafka:
    properties:
      session:
        timeout:
          ms: 45000
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config:
        mechanism: PLAIN
    bootstrap-servers:

client:
  id:

server:
  port: 4080

vendor:
  market:
    data:
      stub:
        url: "http://localhost:3080"
  kafka:
    key:
    secret:

#logging:
#  level:
#    root: DEBUG