spring:
  application:
    name: fxMarketDataConnector
  kafka:
    properties:
      session:
        timeout:
          ms: 45000
    bootstrap-servers: localhost:9092

server:
  port: 4080

vendor:
  market:
    data:
      stub:
        url: "http://localhost:3080"
