spring:
  application:
    name: fxMarketDataProcessor

server:
  port: 4081

kafka:
  bootstrap-servers: PLAINTEXT://broker:29092
  topic: fx-rates
  application-id-config: fx-market-processor-stream-operator
