spring:
  application:
    name: fxMarketDataProcessor

server:
  port: 4081

kafka:
  bootstrap-servers: PLAINTEXT://localhost:9093
  topic: fx_rates
  application-id-config: fx-market-processor-stream-operator # Each instance needs to have the same value; to cooperate
  application-self-host: fx-market-processor-set-2 # Self host where any other instance can access and connect
  application-self-port: 4081
  application-state-dir-config: /tmp/kafka-streams/fxrates # Where state is stored