#kubectl apply -f gihubSecret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: market-data-processor-private-repository
    namespace: argocd
    labels:
      argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Jereczek/market-data-processor.git
  username: argocd-private-repo
  password: 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