spring:
  application:
    name: FlinkOrchestrator

server:
  port: 8080

flink:
  url: "http://fx-flink-jobmanager:8081"
  jobs:
    - name: fxmarketflinkproces
      arguments:
        topic: fx_rates
        bootstrapServers: kafka:9071
    - name: fxmarketflinkconnector
      arguments:
        stub_hostname: fx-market-data-stub-ws-svc
        stub_port: 3081
