spring:
  application:
    name: fxMarketCamelDataProcessor

server:
  port: 8080

kafka:
  bootstrap-servers: PLAINTEXT://kafka:9092
  # test with kafka-console-consumer  --bootstrap-server PLAINTEXT://kafka:9092 --topic fx_rates_camel