// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxMarketMessage.proto

package com.fx.market.flink.processor.model;

public interface FxRateProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fx.market.kafka.message.FxRateProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string pair = 1;</code>
   */
  String getPair();
  /**
   * <code>optional string pair = 1;</code>
   */
  com.google.protobuf.ByteString
      getPairBytes();

  /**
   * <code>optional string baseCurrency = 2;</code>
   */
  String getBaseCurrency();
  /**
   * <code>optional string baseCurrency = 2;</code>
   */
  com.google.protobuf.ByteString
      getBaseCurrencyBytes();

  /**
   * <code>optional string quoteCurrency = 3;</code>
   */
  String getQuoteCurrency();
  /**
   * <code>optional string quoteCurrency = 3;</code>
   */
  com.google.protobuf.ByteString
      getQuoteCurrencyBytes();

  /**
   * <code>optional string ask = 4;</code>
   */
  String getAsk();
  /**
   * <code>optional string ask = 4;</code>
   */
  com.google.protobuf.ByteString
      getAskBytes();

  /**
   * <code>optional string bid = 5;</code>
   */
  String getBid();
  /**
   * <code>optional string bid = 5;</code>
   */
  com.google.protobuf.ByteString
      getBidBytes();
}
