- route:
    from:
      uri: "kamelet:http-source"
      parameters:
        url: "http://market-data-stub-svc.fxmarket.svc.cluster.local:3080"
        period: 1000
      steps:
        - to:
            uri: "log:info"
        - to:
            uri: "kafka:EURUSD?brokers=PLAINTEXT://kafka.kafka:9092"
        #- to:
        #    uri: "kafka:EURUSD?brokers=my-cluster-kafka-bootstrap.kafka:9092"
            #.setHeader(KafkaConstants.KEY, constant("Camel")) // Key of the message
            #"kamelet:log-sink"
        #- to: "knative:event/fx-market.eurusd"
        #- setBody:
        #    jsonpath: "$.data[*].quotes[*]"
        #- setHeader:
        #    KafkaConstants.KEY: "Camel" # Key of the message

